### ISSUE TITLE
Could not locate boot/core__init.class or boot/core.clj on classpath.

### ISSUE THREAD

**Issue by alexander-yakushev** [tolitius/boot-check#1]
I can't use any command from boot-check because I get this exception. Apparently the pod cannot load boot.core. Any ideas?

**Comment by tolitius** [comment]
looks like a boot-core dep might be missing from your `build.boot`.

I just created a [check boot check](https://github.com/tolitius/check-boot-check), so you can clone and run. Let me know if it solves it.

**Comment by alexander-yakushev** [comment]
Thanks! It was that, and also I had boot `2.4.2` in my `boot.properties`.
