### ISSUE TITLE
bikeshed update

### ISSUE THREAD

**Issue by wontheone1** [tolitius/boot-check#16]
bikeshed could be updated to 0.5.1

**Comment by tolitius** [comment]
done, it's in [tolitius/boot-check "0.1.7"](https://clojars.org/tolitius/boot-check/versions/0.1.7)

bikeshed chaged their API a little, added changes to [README](https://github.com/tolitius/boot-check#bikeshed-options) and to [CHANGELOG](https://github.com/tolitius/boot-check/blob/master/CHANGELOG.md#017)

**Comment by wontheone1** [comment]
@tolitius thanks !!
