### ISSUE TITLE
Eastwood :debug #{:compare-forms}

### ISSUE THREAD

**Issue by garrett-hopper** [tolitius/boot-check#19]
Why is `:debug #{:compare-forms}` set for eastwood?
The output files are rather annoying, as there's no easy way to divert them elsewhere.

**Comment by voytech** [comment]
@Jumblemuddle  @tolitius I think that's my fault. I didn't remove it before pull request ;(

**Comment by garrett-hopper** [comment]
@voytech No worries. I figured maybe it was using that for it's analysis or something. I checked the past few versions and it seemed to be there. (Though I might've been checking wrongly.

Any chance we can get a new release without that sometime?

**Comment by tolitius** [comment]
fixed by #21
