### ISSUE TITLE
Old Dependencies

### ISSUE THREAD

**Issue by jimrthy** [tolitius/boot-check#23]
YAGNI is at 0.1.7, but this uses 0.1.6.

kibit is at 0.1.6, but this uses 0.1.5 (this one is a really big deal: they added support for namespaced keywords).

eastwood is up to 0.3.3, but this uses 0.2.5

It looks like it should be straightforward to update the versions, and hopefully Rich's lessons have been followed so these would all be safe. I can easily slap together a PR to bump the versions, but I'm iffy about testing it.

**Comment by tolitius** [comment]
all are updated in `0.1.12`

who is this guy Rich, what are his lessons, and why should they be followed?

**Comment by jimrthy** [comment]
Sweet! Thank you.

I forget his last name. Rich Richie, maybe? Richie Rich? Something along those lines.
