### ISSUE TITLE
Could not locate tolitius /boot/helper__init.class or tolitius/boot/helper.clj on classpath.

### ISSUE THREAD

**Issue by crinklywrappr** [tolitius/boot-check#4]
New to boot.  I wanted to define check-sources in profile.boot but am getting this error when running boot check-sources on this project: https://github.com/magomimmo/modern-cljs/blob/master/doc/second-edition/tutorial-01.md

I can browse to the file in the the local maven repo, and `boot show -c` shows it in the classpath.

profile.boot:

```
(set-env! :dependencies '[[boot-deps "0.1.6"]
                          [tolitius/boot-check "0.1.3"]])

(require '[boot.repl]
         '[tolitius.boot-check :as check]
         '[boot-deps :refer [ancient]])

(swap! boot.repl/*default-dependencies* conj
       '[refactor-nrepl "2.0.0-SNAPSHOT"]
       '[cider/cider-nrepl "0.10.0-SNAPSHOT"])

(swap! boot.repl/*default-middleware* conj
       'refactor-nrepl.middleware/wrap-refactor)

(deftask check-sources []
  (comp
   (check/with-yagni)
   (check/with-bikeshed)
   (check/with-kibit)
   (check/with-eastwood)))

```

build.boot (in my project)

```
(set-env!
 :source-paths #{"src/cljs"}
 :resource-paths #{"html"}
 :dependencies '[[adzerk/boot-cljs "1.7.170-3"]])

(require '[adzerk.boot-cljs :refer [cljs]])
```

**Comment by crinklywrappr** [comment]
Same error in the repl.

**Comment by tolitius** [comment]
check the [demo boot-check project](https://github.com/tolitius/check-boot-check), you might need to add a `boot-core` as a "provided" dep as [shown here](https://github.com/tolitius/check-boot-check/blob/master/build.boot#L3-L4).

there is [an ask](https://github.com/tolitius/boot-check/issues/2) to remove `boot-core` dep which I agree with but it would have to be a pull request at this point.

let me know if it worked for you

**Comment by crinklywrappr** [comment]
I had to place both libraries as deps in build.boot.  Placing them both in profile.boot didn't do any good.

**Comment by tolitius** [comment]
closing this. feel free to reopen if there are more questions

**Comment by dancmeyers** [comment]
This is probably because you have done the same as me, and your `build.boot` specifies dependencies as a quoted vector of vectors, i.e.
```
(set-env! :dependencies   '[[org.clojure/clojure "1.8.0"]
                            [com.taoensso/timbre  "4.7.4"]
...
```

so the `set-env` for dependencies in your `profile.boot` is thrown away/overwritten before the `check-sources` function is actually run. You can fix this by setting your dependencies using a `conj`/`contact` etc onto the existing dependencies list in `build.boot`, but that may come with it's own problems. I'm still trying to find an easier way.
