### ISSUE TITLE
Add verbose option to bikeshed

### ISSUE THREAD

**Issue by ghost** [tolitius/boot-check#5]
Currently, I am not able to list the missing docstrings when I run `check/with-bikeshed`.

I took a quick look at the code and it seems to me that this option would need to
be added to the boot task.

I'll have a more in-depth look at this in the following days, to see if I am able to add this feature.

Is it something you guys would be interested in having?

**Comment by tolitius** [comment]
sure, if that's helpful, we'll be very interested :)

should be in `0.1.4-SNAPSHOT`

Check it out: https://github.com/tolitius/boot-check#bikeshed-options

Let me know of it works for you.
