### ISSUE TITLE
Configure checkers through tasks

### ISSUE THREAD

**Issue by AdamFrey** [tolitius/boot-check#7]
Just wondering if you had a plan to pass arguments from the boot tasks down to the checkers themselves (like excluded namespaces, excluded linters, etc.).

Would you accept a PR that implemented some subset of argument passing or would you like to cover everything at once?

**Comment by snorremd** [comment]
Would like to see that as well. The default 80 character limit of Bikeshed is overly strict so would be very nice if I could pass the `--max-line-length` argument down via the check-with-bikeshed task.

**Comment by tolitius** [comment]
would `-o` + map not work for you?

i.e.

```bash
$ boot check/with-bikeshed -o "{:max-line-length 42}"

Checking for lines longer than 42 characters.
Badly formatted files:
## ....
```

**Comment by tolitius** [comment]
@AdamFrey which options are you looking to add? _Some_ options are already supported via `-o` / `--options`, and bikeshed: https://github.com/tolitius/boot-check#bikeshed-options.

**Comment by snorremd** [comment]
@tolitius I was not aware of that option, though reading the README.md now in hindsight makes it quite obvious. Today I learned, and so forth. Then I've got everything I need, thank you.

**Comment by tolitius** [comment]
closing this. feel free to reopen if there are more questions
